### ISSUE TITLE
Missing item in menu

### ISSUE THREAD

**Issue by lamnguyencse17** [Foodgether/foodgether#1]
Reproduce step:
- Enter url: https://shopeefood.vn/ho-chi-minh/quan-an-com-tam-31-dong-den
- Scroll to the end of the UI and compare the last item in the menu

Expected result: will find "Cơm thêm"
Actual result: not found
Likely cause: not getting all the items

**Comment by tainguyent** [comment]
i need cơm thêm

**Comment by lamnguyencse17** [comment]
> i need cơm thêm

No cơm thêm for u
