### ISSUE TITLE
Basic Login/Register work

### ISSUE THREAD

**Issue by lamnguyencse17** [Foodgether/foodgether#2]
The site currently does not have Login/Register feature and it needs one to identify the user

- Frontend:
  - Form to login/register using tabs
    - Register using Phone, Name, Pin
    - Login using Phong and Pin
  - Store JWT token from backend
  - Request for JWT validation on entering page
- Backend:
  - Verify PIN, Phone and provide JWT Token
  - Register new user and provide JWT Token (index on phone)
  - Verify JWT Token on request

**Comment by tainguyent** [comment]
vip
